/* test_vapi.c generated by valac, the Vala compiler
 * generated from test_vapi.vala, do not modify */

/*file to test that does the vapi works fine*/

#include <glib.h>
#include <glib-object.h>
#include <supplicant.h>
#include <stdio.h>

#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))



gint _main (void);



gint _main (void) {
	gint result;
	gchar* _tmp0_;
	gint msg_size;
	gint msg_length1;
	gchar* msg;
	GString* sb;
	ruijie_start_auth ((gchar*) "username", (gchar*) "password", (gchar*) "eth012", 3);
	ruijie_stop_auth ();
	msg = (_tmp0_ = g_new0 (gchar, 200), msg_length1 = 200, msg_size = msg_length1, _tmp0_);
	ruijie_get_server_msg (msg, msg_length1);
	sb = g_string_new ("");
	{
		gchar* c_collection;
		int c_collection_length1;
		int c_it;
		c_collection = msg;
		c_collection_length1 = msg_length1;
		for (c_it = 0; c_it < msg_length1; c_it = c_it + 1) {
			gchar c;
			c = c_collection[c_it];
			{
				if (c == '\0') {
					break;
				}
				g_string_append_printf (sb, "%c", (gint) c);
			}
		}
	}
	fprintf (stdout, "get_msg:%s\n", sb->str);
	ruijie_echo ();
	result = 0;
	msg = (g_free (msg), NULL);
	_g_string_free0 (sb);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _main ();
}




