/* dbus.h generated by valac, the Vala compiler, do not modify */


#ifndef __DBUS_H__
#define __DBUS_H__

#include <glib.h>

G_BEGIN_DECLS


typedef gint (*Fuction) (void* user_data);

gint connect_to_sig_StateChanged (Fuction fast, void* fast_target);
gint g_loop_run (void);
gint g_loop_quit (void);
gint dbus_init (void);
gboolean is_networ_ready (void);


G_END_DECLS

#endif
